/// <reference types="node" />
/**
 * Server-side helpers for Convex JWT auth.
 *
 * Import from `convex-simple-auth/server` inside files under your `convex/`
 * directory. Pairs with a JWKS data URI inlined in `convex/auth.config.ts`
 * (generated by `convex-simple-auth-keys`).
 */
import { defineTable, type AuthConfig } from "convex/server";
import { v } from "convex/values";
import { SignJWT, importPKCS8 } from "jose";

// -- auth.config.ts helper --------------------------------------------------

/**
 * Wraps a JWKS object into the `customJwt` provider entry expected by
 * `convex/auth.config.ts`. Use as:
 *
 *   export default { providers: [jwksProvider(JWKS)] } satisfies AuthConfig;
 */
export function jwksProvider(
  jwks: object,
): NonNullable<AuthConfig["providers"]>[number] {
  return {
    type: "customJwt",
    issuer: process.env.CONVEX_SITE_URL!,
    jwks: "data:application/json;base64," + btoa(JSON.stringify(jwks)),
    algorithm: "ES256",
    applicationID: "convex",
  };
}

// -- schema -----------------------------------------------------------------

/**
 * Spread into your `defineSchema({ ... })` to add a `users` table indexed by
 * email. Both fields are optional so anonymous users (no email/password) fit
 * the same row shape.
 */
export const authTables = {
  users: defineTable({
    email: v.optional(v.string()),
    passwordHash: v.optional(v.string()),
  }).index("by_email", ["email"]),
};

// -- password hashing (PBKDF2-SHA-256, OWASP 2023 iters) --------------------

const PBKDF2_ITERATIONS = 600_000;
const SALT_BYTES = 16;
const KEY_BITS = 256;

const enc = new TextEncoder();

async function pbkdf2(password: string, salt: Uint8Array): Promise<Uint8Array> {
  const km = await crypto.subtle.importKey(
    "raw",
    enc.encode(password.normalize("NFKC")),
    "PBKDF2",
    false,
    ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    {
      name: "PBKDF2",
      salt: salt as BufferSource,
      iterations: PBKDF2_ITERATIONS,
      hash: "SHA-256",
    },
    km,
    KEY_BITS,
  );
  return new Uint8Array(bits);
}

const toHex = (b: Uint8Array) =>
  Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");

const fromHex = (h: string) => {
  const match = h.match(/../g);
  if (!match) return new Uint8Array(0);
  return new Uint8Array(match.map((byte) => parseInt(byte, 16)));
};

/** Returns `"<saltHex>:<keyHex>"`. Safe to store as a string column. */
export async function hashPassword(password: string): Promise<string> {
  const salt = crypto.getRandomValues(new Uint8Array(SALT_BYTES));
  return `${toHex(salt)}:${toHex(await pbkdf2(password, salt))}`;
}

/** Constant-time compare. Returns false on malformed input. */
export async function verifyPassword(
  password: string,
  stored: string,
): Promise<boolean> {
  const [s, h] = stored.split(":");
  if (!s || !h) return false;
  const expected = fromHex(h);
  const computed = await pbkdf2(password, fromHex(s));
  if (computed.length !== expected.length || expected.length === 0) return false;
  let diff = 0;
  for (let i = 0; i < computed.length; i++) {
    diff |= (computed[i] ?? 0) ^ (expected[i] ?? 0);
  }
  return diff === 0;
}

// -- JWT signing ------------------------------------------------------------

const ALGORITHM = "ES256";
const AUDIENCE = "convex";
/** Must match the `kid` on the JWK inside your `convex/auth.config.ts`. */
const KEY_ID = "default";
const DEFAULT_TTL_SECONDS = 60 * 60 * 24 * 7;

let cachedKey: Awaited<ReturnType<typeof importPKCS8>> | null = null;

async function getPrivateKey() {
  if (cachedKey !== null) return cachedKey;
  const pem = process.env.JWT_PRIVATE_KEY;
  if (!pem) throw new Error("JWT_PRIVATE_KEY is not set");
  cachedKey = await importPKCS8(pem, ALGORITHM);
  return cachedKey;
}

export interface SignJwtOptions {
  /** TTL in seconds. Defaults to 7 days. */
  ttlSeconds?: number;
  /** Extra JWT claims merged into the payload. */
  claims?: Record<string, unknown>;
}

/**
 * Mint an ES256 JWT whose `sub` is your `users._id`. `ctx.auth.getUserIdentity()`
 * inside queries/mutations will return `{ subject: sub, ...claims }`.
 */
export async function signJwt(
  sub: string,
  { ttlSeconds = DEFAULT_TTL_SECONDS, claims = {} }: SignJwtOptions = {},
): Promise<string> {
  const issuer = process.env.CONVEX_SITE_URL;
  if (!issuer) throw new Error("CONVEX_SITE_URL is not set");
  const key = await getPrivateKey();
  return new SignJWT(claims)
    .setProtectedHeader({ alg: ALGORITHM, typ: "JWT", kid: KEY_ID })
    .setSubject(sub)
    .setIssuer(issuer)
    .setAudience(AUDIENCE)
    .setIssuedAt()
    .setExpirationTime(Math.floor(Date.now() / 1000) + ttlSeconds)
    .sign(key);
}

// -- utilities --------------------------------------------------------------

export const normalizeEmail = (email: string) => email.trim().toLowerCase();
